### ISSUE TITLE
Team Drive Project Folder Cleanup

### ISSUE THREAD

**Issue by stdavis** [agrc/porter#80]
Should we add a checkbox to the deprecation template for cleaning up the Project folder in the AGRC Projects Google Drive Team Drive? If so, what should the action be? Delete the folder 😬? Move it to some archive folder (this would be my vote)?

**Comment by steveoh** [comment]
Archiving to a folder like historic or past projects seems reasonable. I could see some items just being deleted though. I will admit that the use of that area is spotty on my end; I actually forgot about it. Does it have a lot of items that need removing in your opinion?

**Comment by stdavis** [comment]
I think that there are items in there that should be cleaned up such as GeoEvent. There's a ton of folders in there. I'm interested in keeping it manageable.

**Comment by nathankota** [comment]
A checkbox on the deprecation template is a good idea, as is an archiving folder. Indeed, there is some junk that can be deleted rather than archived. I have some skin in this game because I utilize the Projects folder, including adding some junk; however, I have tried not to touch anything that was before my time. There are some organizational issues that seem to have developed over time. DNR is a good example, where there is a specific folder for the agency as a whole, but also several individual folders (and even some duplicates) at the same hierarchical level that should be embedded within DNR (e.g. GeoEvent, Roadkill, Wildlife Vehicle Tracking (duplicate), FFSL, DOGM, WRI, UGS). An archive folder should probably match the active projects folder hierarchy as closely as possible.

**Comment by steveoh** [comment]
Ok. It sounds like a check box to triage the folder data is a nice reminder. It also sounds like a rough pass over the entire folder would be a helpful task to complete async. Nathan do you want to take a shot at organizing that since you are a power user? I wouldn't shy away from the items older than you.

**Comment by nathankota** [comment]
Yes, will do. It's on my trello (step 1) and I will work it in asap.
